# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

xcodeproj = "GHCollection.xcodeproj"

platform :ios do
  
  desc 'Increments version patch number, new patch. E.g. 1.0.2->1.0.3'
  lane :increment_version_patch do
    increment_build_number(
      build_number: '1',
      xcodeproj: xcodeproj
    )
    increment_version_number(
      bump_type: 'patch',
      xcodeproj: xcodeproj
    )
  end

  desc 'Increments version minor number, new patch. E.g. 1.8.2->1.9.0'
  lane :increment_version_minor do
    increment_build_number(
      build_number: '1',
      xcodeproj: xcodeproj
    )
    increment_version_number(
      bump_type: 'minor',
      xcodeproj: xcodeproj
    )
  end

  desc 'Increments build number'
  lane :bump_build do
    increment_build_number(
      xcodeproj: xcodeproj
    )
  end
end
